stages:
    - code-quality
    - package
    
cache:
    paths:
        - node_modules/
    
# lint:
#    stage: code-quality
#    image: node:latest
#    script:
#        - npm install
#        - npm run lint

build:
    stage: package
    image: node:latest
    script:
        - npm install
        - npm run electron:build
    artifacts:
        paths:
            - 'release/*.deb'
            - 'release/*.AppImage'
            - 'release/*.snap'